# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChinmayaEchoes' do
  pod 'AppCenter/Crashes', '~> 1.10.0'
  pod 'AppCenter/Analytics', '~> 1.10.0'
  pod 'AppCenterReactNativeShared', '~> 1.9.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ChinmayaEchoes

  pod 'XCDYouTubeKit', '~> 2.5'

  platform :ios, '9.0'

  pod 'react-native-youtube', :path => '../node_modules/react-native-youtube'

  pod 'react-native-video', :path => '../node_modules/react-native-video'

  pod 'RNAWSCognito', :path => '../node_modules/amazon-cognito-identity-js'

  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'

  pod 'react-native-orientation', :path => '../node_modules/react-native-orientation'

  target 'ChinmayaEchoesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ChinmayaEchoes-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ChinmayaEchoes-tvOS

  target 'ChinmayaEchoes-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
